### ISSUE TITLE
MIT License file?

### ISSUE THREAD

**Issue by esksak** [develar/fs-extra-p#2]
Hi, we would like to credit the module to our app's acknowledgement, 
however there seems no LICENSE file nor description on README. 
According to the package.json, this module is under MIT license. 
Could you point me out where the license 	is?
As far as I understand, We need to know at least the copyright.
Thanks in advance.

**Comment by RobertBorg** [comment]
I'd love if this file was part of the distributions as well.
It's missing from here https://unpkg.com/browse/bluebird-lst@latest/
